Цели данного модуля:

1. Научиться сортировать данные.
2. Получить навыки группировки данных и анализа групп.
3. Освоить методы построения сводных таблиц и научиться с их помощью исследовать зависимости в признаках.
4. Научиться работать с данными, представленными в виде нескольких таблиц, и познакомиться с методами их объединения.

In [3]:
import pandas as pd 

melb_data = pd.read_csv('data/melb_data_fe.csv')
melb_df = melb_data.copy()

display(melb_df.head(10))

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend
0,Abbotsford,2,house,1480000.0,S,Biggin,2016-03-12,2.5,3067,2,...,144.9984,Northern Metropolitan,4019,25.200000,-0.231707,3,46,5,St,1
1,Abbotsford,2,house,1035000.0,S,Biggin,2016-04-02,2.5,3067,2,...,144.9934,Northern Metropolitan,4019,15.800000,-0.327660,4,116,5,St,1
2,Abbotsford,3,house,1465000.0,SP,Biggin,2017-04-03,2.5,3067,3,...,144.9944,Northern Metropolitan,4019,18.750000,0.056338,4,117,0,St,0
3,Abbotsford,3,house,850000.0,PI,Biggin,2017-04-03,2.5,3067,3,...,144.9969,Northern Metropolitan,4019,15.750000,0.145455,4,47,0,other,0
4,Abbotsford,4,house,1600000.0,VB,Nelson,2016-04-06,2.5,3067,3,...,144.9941,Northern Metropolitan,4019,17.750000,0.083969,4,2,2,St,0
5,Abbotsford,2,house,941000.0,S,Jellis,2016-07-05,2.5,3067,2,...,144.9953,Northern Metropolitan,4019,25.200000,-0.179153,7,46,1,St,0
6,Abbotsford,3,house,1876000.0,S,Nelson,2016-07-05,2.5,3067,4,...,144.9993,Northern Metropolitan,4019,23.333333,-0.076923,7,106,1,St,0
7,Abbotsford,2,house,1636000.0,S,Nelson,2016-08-10,2.5,3067,2,...,144.9954,Northern Metropolitan,4019,21.400000,-0.410468,8,126,2,St,0
8,Abbotsford,1,unit,300000.0,S,Biggin,2016-08-10,2.5,3067,1,...,144.9973,Northern Metropolitan,4019,42.000000,1.000000,8,46,2,St,0
9,Abbotsford,2,house,1097000.0,S,Biggin,2016-08-10,2.5,3067,3,...,144.9989,Northern Metropolitan,4019,12.500000,-0.491525,8,116,2,St,0

## Задание 1.1
Преобразуйте столбец Date в формат datetime и выделите квартал (quarter) продажи объектов недвижимости. Найдите второй по популярности квартал продажи. В качестве ответа запишите число объектов, проданных в этом квартале.

In [2]:
melb_df['Date'] = pd.to_datetime(melb_df['Date'], format='mixed', dayfirst=True)

display(melb_df['Date'].dt.quarter.value_counts())

Date
3    5377
2    4808
4    2272
1    1123
Name: count, dtype: int64

## Задание 1.2
Преобразуйте все столбцы, в которых меньше 150 уникальных значений, в тип данных category, исключив из преобразования столбцы Date, Rooms, Bedroom, Bathroom, Car.
В качестве ответа запишите результирующее количество столбцов, которые имеют тип данных category.

In [3]:
excluds_list = ['Date', 'Rooms', 'Bedroom', 'Bathroom', 'Car']
for col in melb_df.columns:
    if melb_df[col].nunique() < 150 and col not in excluds_list:
        melb_df[col] = melb_df[col].astype('category')
display(melb_df.dtypes.value_counts())

float64           8
int64             7
category          1
category          1
category          1
category          1
datetime64[us]    1
category          1
category          1
category          1
category          1
category          1
category          1
Name: count, dtype: int64

## sort_values()

- by — имя или список имён столбцов, по значениям которых производится сортировка.
- axis — ось, по которой производится сортировка (0 — строки, 1 — столбцы). По умолчанию сортировка производится по строкам.
- ascending — сортировка по возрастанию (от меньшего к большему). По умолчанию параметр выставлен на True, для сортировки по убыванию (от большего к меньшему) необходимо выставить его на False.
- ignore_index — создаются ли новые индексы в таблице. По умолчанию выставлен на False и сохраняет индексы изначальной таблицы.
- inplace — производится ли замена исходной таблицы на отсортированную. По умолчанию параметр выставлен на False, то есть замены не производится. Чтобы переопределить исходную таблицу на отсортированную, необходимо выставить этот параметр на True.

In [9]:
# сортировка по назавнию столбца 
display(melb_df.sort_values(by='Date',ascending=True))

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend
6184,Surrey Hills,3,house,1205000.0,S,Fletchers,2016-01-28,11.2,3127,3,...,145.10060,Southern Metropolitan,5457,18.000000,-0.590909,1,46,3,Rd,0
6183,Surrey Hills,2,unit,813000.0,S,Fletchers,2016-01-28,11.2,3127,2,...,145.10230,Southern Metropolitan,5457,25.200000,0.076923,1,46,3,Rd,0
4029,Mont Albert,2,unit,750000.0,S,RW,2016-02-04,11.8,3127,2,...,145.10980,Eastern Metropolitan,2079,13.333333,1.000000,4,13,5,Rd,1
7168,Ormond,1,unit,250000.0,VB,Ray,2016-02-04,11.8,3204,1,...,145.04750,Southern Metropolitan,3578,12.000000,1.000000,4,56,5,St,1
4709,Port Melbourne,2,unit,550000.0,S,Buxton,2016-02-04,3.8,3207,2,...,144.94000,Southern Metropolitan,8648,11.400000,1.000000,4,4,5,St,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13244,Murrumbeena,3,house,1321188.0,SP,Woodards,2017-09-23,10.1,3163,3,...,145.07250,Southern Metropolitan,4442,28.571429,-0.491094,9,72,5,St,1
13243,other,3,house,840000.0,S,Ray,2017-09-23,18.8,3170,3,...,145.17792,South-Eastern Metropolitan,7113,15.285714,-0.719528,9,45,5,Dr,1
13242,other,5,house,880000.0,PI,other,2017-09-23,18.8,3170,5,...,145.17372,South-Eastern Metropolitan,7113,9.692308,-0.676923,9,57,5,St,1
13240,other,4,house,1080000.0,S,Ray,2017-09-23,18.8,3170,4,...,145.19475,South-Eastern Metropolitan,7113,20.400000,-0.635063,9,37,5,Ct,1
13119,Brighton East,5,house,2750000.0,S,Buxton,2017-09-23,10.3,3187,5,...,145.02003,Southern Metropolitan,6938,9.692308,-0.664894,9,47,5,Av,1

## Сортировка по значениям нескольких столбцов

Для сортировки по значениям нескольких столбцов необходимо передать названия этих столбцов в параметр by в виде списка. При этом важно обращать внимание на порядок следования столбцов.
Мы получили таблицу, отсортированную по возрастанию расстояния до центра города. Если встречаются объекты недвижимости, у которых расстояние оказывается одинаковым, то внутри такой группы производится сортировка по цене объекта.

In [10]:
melb_df.sort_values(by=['Distance', 'Price']).loc[::10, ['Distance', 'Price']]

       Distance      Price
11428       0.0   387000.0
10512       0.7   600000.0
5727        1.2   485000.0
8671        1.2   595000.0
5736        1.2   740000.0
...         ...        ...
12011      38.0   680000.0
10673      38.0   810000.0
13429      38.0  1155000.0
11102      41.0   650000.0
12728      45.9   650000.0

[1358 rows x 2 columns]

In [ ]:
mask1 = melb_df['AreaRatio'] < -0.8
mask2 = melb_df['Type'] == 'townhouse'
mask3 = melb_df['SellerG'] == 'McGrath'
melb_df[mask1 & mask2 & mask3].sort_values(
    by=['Date', 'AreaRatio'],
    ascending=[True, False],
    ignore_index=True
).loc[:, ['Date', 'AreaRatio']]d

        Date  AreaRatio
0 2016-07-26  -0.974922
1 2016-09-24  -0.971831
2 2016-11-12  -0.945946
3 2016-11-27  -0.953608
4 2017-04-08  -0.947368
5 2017-04-08  -0.970874

Произведите сортировку столбца AreaRatio по убыванию. После сортировки замените индексы таблицы на новые. Какое значение площади здания находится в строке 1558? Ответ округлите до целого числа.

In [22]:
melb_df = melb_df.sort_values(by='AreaRatio', ascending=False)
melb_df = melb_df.reset_index(drop=True)

value = melb_df.loc[1558, 'AreaRatio']
print(value)

1.0

Задание 2.3

Найдите таунхаусы (Type) с количеством жилых комнат (Rooms) больше 2. Отсортируйте полученную таблицу сначала по возрастанию числа комнат, а затем по убыванию средней площади комнат (MeanRoomsSquare). Индексы таблицы замените на новые. Какая цена будет у объекта в строке 18? Ответ запишите в виде целого числа.

In [38]:
mask11 = melb_df[(melb_df['Type'] == 'townhouse') & (melb_df['Rooms'] > 2)]
mask11 = mask11.sort_values(by=['Rooms','MeanRoomsSquare'],ascending=[False,True])
mask11 = mask11.reset_index(drop=True)
value1 = mask11.loc[18,'Price']
display(round(value1))

1202000

Сгруппируйте данные по признаку количества комнат и найдите среднюю цену объектов недвижимости в каждой группе. В качестве ответа запишите количество комнат, для которых средняя цена наибольшая.

In [8]:
import pandas as pd
melb_data = pd.read_csv('data/melb_data_fe.csv', sep=',')
melb_df = melb_data.copy()

melb_df.groupby('Rooms')['Price'].mean().sort_values(ascending=False)

Rooms
7     1.920700e+06
5     1.870260e+06
6     1.849366e+06
8     1.602750e+06
4     1.445282e+06
3     1.076081e+06
10    9.000000e+05
2     7.750812e+05
1     4.338245e+05
Name: Price, dtype: float64

Задание 3.2

Какой регион имеет наименьшее стандартное отклонение по географической широте (Lattitude)?

В качестве ответа запишите название этого региона.

In [13]:
melb_df.head()

melb_df.groupby('Regionname')['Longtitude'].min().sort_values()

Regionname
Western Victoria              144.43181
Northern Victoria             144.48571
Western Metropolitan          144.59864
Northern Metropolitan         144.84960
Southern Metropolitan         144.91830
Eastern Metropolitan          145.02870
South-Eastern Metropolitan    145.05593
Eastern Victoria              145.14928
Name: Longtitude, dtype: float64

Задание 3.3

Какая риелторская компания (SellerG) имеет наименьшую общую выручку за период с 1 мая по 1 сентября (включительно) 2017 года?

Для ответа на этот вопрос рассчитайте сумму продаж (Price) каждой компании в заданный период.`

In [33]:
melb_data['Date'] = pd.to_datetime(melb_data['Date'])
melb_data.head()

may = melb_data[melb_data['Date'].dt.month == 5]
sep = melb_data[melb_data['Date'].dt.month == 9]
display(may.head())
display(sep.head())

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend
14,Abbotsford,1,unit,441000.0,SP,Greg,2016-05-14,2.5,3067,1,...,144.9988,Northern Metropolitan,4019,42.000000,1.000000,5,46,5,St,1
36,Abbotsford,2,house,1012500.0,S,Nelson,2016-05-28,2.5,3067,2,...,144.9976,Northern Metropolitan,4019,16.400000,-0.378788,5,116,5,St,1
55,Airport West,5,house,755000.0,PI,other,2016-05-14,13.5,3042,3,...,144.8699,Western Metropolitan,3464,12.600000,-0.650970,5,46,5,Rd,1
69,Airport West,3,house,685000.0,S,Barry,2016-05-22,13.5,3042,3,...,144.8733,Western Metropolitan,3464,16.142857,-0.673410,5,41,6,Rd,1
104,Albert Park,2,unit,647000.0,S,Greg,2016-05-22,3.3,3206,2,...,144.9542,Southern Metropolitan,3280,25.200000,1.000000,5,46,6,Rd,1

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend
18,Abbotsford,3,house,955000.0,S,Collins,2016-09-17,2.5,3067,3,...,144.9975,Northern Metropolitan,4019,18.000000,-0.184466,9,46,5,St,1
19,Abbotsford,2,house,890000.0,S,Biggin,2016-09-17,2.5,3067,2,...,145.0004,Northern Metropolitan,4019,14.600000,-0.345291,9,31,5,St,1
30,Abbotsford,4,house,1542000.0,S,Collins,2016-09-24,2.5,3067,4,...,144.9965,Northern Metropolitan,4019,11.454545,1.000000,9,46,5,St,1
62,Airport West,3,house,910000.0,S,McDonald,2016-09-17,13.5,3042,3,...,144.8835,Western Metropolitan,3464,18.000000,-0.720311,9,46,5,St,1
63,Airport West,4,house,773000.0,S,Brad,2016-09-17,13.5,3042,5,...,144.8679,Western Metropolitan,3464,25.750000,-0.264286,9,36,5,St,1