## Задача 1 — разведка данных (easy)

Сделай:
- Выведи первые 5 строк
- Посмотри типы данных (dtypes)
- Найди количество пропусков в каждом столбце

In [6]:
import pandas as pd

melb_df = pd.read_csv('data/melb_data.csv', sep=',')

display(melb_df.head(5))
display(melb_df.info())
# Isnull = пропущенные значения
display(melb_df.isnull().sum())

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1,202.0,126.0,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0,156.0,79.0,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0,134.0,150.0,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019,"-37.8093, 144.9944"
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1,94.0,126.0,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,"-37.7969, 144.9969"
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2,120.0,142.0,2014,Yarra,-37.8072,144.9941,Northern Metropolitan,4019,"-37.8072, 144.9941"

<class 'pandas.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  str
 2   Address        13580 non-null  str
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  str
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  str
 7   SellerG        13580 non-null  str
 8   Date           13580 non-null  str
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  int64
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  int64
 17  CouncilArea    12211 non-null  str
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  str
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  str
dtypes: float64(6), int64(8), str(9)
memory usage: 2.4 MB

None

index               0
Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom             0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
YearBuilt           0
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
Coordinates         0
dtype: int64

## Задача 2 — фильтрация (easy+)
Найди:
- Дома в районе Suburb == "Richmond"
- С ценой (Price) больше 1,000,000
- И количеством комнат (Rooms) ≥ 3

In [10]:
# home "Richmond"
richmond_houses = melb_df[melb_df['Suburb'] == 'Richmond'][melb_df['Price'] > 1000000][melb_df['Rooms']>=3] 
display(richmond_houses.head(10))

C:\Users\user\AppData\Local\Temp\ipykernel_2748\3983866772.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  richmond_houses = melb_df[melb_df['Suburb'] == 'Richmond'][melb_df['Price'] > 1000000][melb_df['Rooms']>=3]
C:\Users\user\AppData\Local\Temp\ipykernel_2748\3983866772.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  richmond_houses = melb_df[melb_df['Suburb'] == 'Richmond'][melb_df['Price'] > 1000000][melb_df['Rooms']>=3]

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
5257,5257,Richmond,81 Erin St,3,h,1260000.0,S,Biggin,3/09/2016,2.6,...,0,203.0,81.0,1900,Yarra,-37.8166,144.9945,Northern Metropolitan,14949,"-37.8166, 144.9945"
5258,5258,Richmond,52 Lyndhurst St,3,t,1236000.0,S,Jellis,3/09/2016,2.6,...,1,675.0,126.0,1970,Yarra,-37.8206,145.0003,Northern Metropolitan,14949,"-37.8206, 145.0003"
5263,5263,Richmond,7 Bank St,3,h,1600000.0,S,hockingstuart,3/12/2016,2.6,...,1,115.0,126.0,1970,Yarra,-37.8163,144.9984,Northern Metropolitan,14949,"-37.8163, 144.9984"
5264,5264,Richmond,29 Bowen St,3,h,2180000.0,PI,Blue,3/12/2016,2.6,...,2,345.0,126.0,1970,Yarra,-37.8159,144.9940,Northern Metropolitan,14949,"-37.8159, 144.994"
5266,5266,Richmond,131 Lord St,4,h,3335000.0,S,Jellis,3/12/2016,2.6,...,2,319.0,126.0,1893,Yarra,-37.8244,145.0044,Northern Metropolitan,14949,"-37.8244, 145.0044"
5268,5268,Richmond,234 Coppin St,3,h,1102000.0,S,Dingle,4/02/2016,2.6,...,0,194.0,126.0,1970,Yarra,-37.8265,145.0022,Northern Metropolitan,14949,"-37.8265, 145.0022"
5272,5272,Richmond,78 Davison St,5,h,3200000.0,SP,Jellis,4/03/2017,2.6,...,3,618.0,260.0,1890,Yarra,-37.8157,145.0073,Northern Metropolitan,14949,"-37.8157, 145.0073"
5279,5279,Richmond,247 Church St,3,h,1010000.0,PI,Jellis,4/06/2016,2.6,...,1,199.0,105.0,1900,Yarra,-37.8193,144.9993,Northern Metropolitan,14949,"-37.8193, 144.9993"
5283,5283,Richmond,21 Gardner St,3,h,1152500.0,S,Biggin,6/08/2016,2.6,...,1,78.0,126.0,1970,Yarra,-37.8154,145.0061,Northern Metropolitan,14949,"-37.8154, 145.0061"
5284,5284,Richmond,33a River St,4,h,1375000.0,S,hockingstuart,6/08/2016,2.6,...,2,58.0,158.0,2007,Yarra,-37.8170,145.0135,Northern Metropolitan,14949,"-37.817, 145.0135"

## Задача 3 — агрегация (medium)
Сделай через groupby():
- Среднюю цену дома по районам (Suburb)
- Отсортируй по убыванию
- Выведи топ-5 самых дорогих районов

groupby — это способ сгруппировать данные по какому-то признаку, чтобы потом что-то с ними сделать.

Агрегация (aggregation)

Агрегация — это сжатие данных внутри группы до одного значения.

Типа:
- среднее (mean)
- сумма (sum)
- количество (count)
- максимум (max)
- минимум (min)

In [22]:
melb_df_arg = melb_df.groupby('Suburb')['Price'].mean()
melb_df_arg = melb_df_arg.sort_values(ascending=False)
top_5_suburbs = melb_df_arg.head(5)
display(top_5_suburbs)

Suburb
Kooyong        2.185000e+06
Canterbury     2.180241e+06
Middle Park    2.082529e+06
Albert Park    1.941355e+06
Brighton       1.930158e+06
Name: Price, dtype: float64

ascending — это направление сортировки
- ascending=True → по возрастанию (от меньшего к большему)
- ascending=False → по убыванию (от большего к меньшему)

## Задача 4 — feature engineering (medium+)
Создай новые признаки:
- price_per_room = Price / Rooms
- price_per_m2 = Price / Landsize
-----
Затем:
- Найди топ-10 домов с самой высокой ценой за комнату

In [25]:
price_per_room = melb_df['Price'] / melb_df['Rooms']
price_per_m2 = melb_df['Price'] / melb_df['Landsize']

display(price_per_room.head(10))

0    740000.000000
1    517500.000000
2    488333.333333
3    283333.333333
4    400000.000000
5    470500.000000
6    625333.333333
7    818000.000000
8    300000.000000
9    548500.000000
dtype: float64

## Задача 5 — мини Data Science (hard)

Подготовь данные для ML:
- Удали строки с пропусками

Выбери признаки:
- Rooms
- Distance
- Landsize

Целевая переменная: Price

any() проверяет: есть ли хотя бы одно True значение

In [56]:
melb_df_copy = melb_df.copy()

def display_null_values(df):
    for column in df.columns:
        # any() проверяет: есть ли хотя бы одно True значение
        if df[column].isnull().any():       
            # Проверяем, есть ли пропущенные значения в столбце
            if pd.api.types.is_numeric_dtype(df[column]):
            # Если столбец числовой (int или float), заменяем пропуски средним значением
                df[column].fillna(df[column].mean(), inplace=True)
            else:
            # Если столбец категориальный (object или string), заменяем пропуски модой (самым частым значением)
                df[column].fillna(df[column].mode()[0], inplace=True)
        return df  # Возвращаем измененный датафрейм

melb_df_copy = display_null_values(melb_df_copy)

melb_df_copy = melb_df_copy[['Rooms', 'Distance', 'Landsize']]

display(melb_df_copy.isnull().sum())

Rooms       0
Distance    0
Landsize    0
dtype: int64

## Задача 1 — фильтрация + логика (must have)

Найди:
- дома с Rooms >= 3
- и Price < 1_000_000

Выведи:
- первые 10 строк
- среднюю цену этих домов

In [64]:
sorted_melb = melb_df[melb_df['Rooms']>=3][melb_df['Price']<1000000]

display(sorted_melb.head(10))
print(f'Средняя цена здания: {round(sorted_melb['Price'].mean())}')

C:\Users\user\AppData\Local\Temp\ipykernel_2748\1656564716.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sorted_melb = melb_df[melb_df['Rooms']>=3][melb_df['Price']<1000000]

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1,94.0,126.0,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,"-37.7969, 144.9969"
18,18,Abbotsford,196 Nicholson St,3,h,955000.0,S,Collins,17/09/2016,2.5,...,0,183.0,126.0,1970,Yarra,-37.8022,144.9975,Northern Metropolitan,4019,"-37.8022, 144.9975"
21,21,Abbotsford,13/11 Nicholson St,3,t,900000.0,S,Beller,18/03/2017,2.5,...,2,0.0,126.0,2010,Yarra,-37.8093,144.9959,Northern Metropolitan,4019,"-37.8093, 144.9959"
38,38,Airport West,154 Halsey Rd,3,t,840000.0,PI,Nelson,3/09/2016,13.5,...,1,303.0,225.0,2016,Moonee Valley,-37.7180,144.8780,Western Metropolitan,3464,"-37.718, 144.878"
39,39,Airport West,50 Bedford St,3,h,730000.0,VB,Nelson,3/12/2016,13.5,...,1,0.0,145.0,1965,Moonee Valley,-37.7203,144.8755,Western Metropolitan,3464,"-37.7203, 144.8755"
40,40,Airport West,50 Bedford St,3,h,770000.0,SP,Nelson,4/03/2017,13.5,...,1,0.0,145.0,1965,Moonee Valley,-37.7203,144.8755,Western Metropolitan,3464,"-37.7203, 144.8755"
42,42,Airport West,1/80 Hawker St,3,t,700000.0,S,Brad,4/03/2017,13.5,...,2,239.0,134.0,2009,Moonee Valley,-37.7218,144.8837,Western Metropolitan,3464,"-37.7218, 144.8837"
43,43,Airport West,1/37 Hillside Gr,3,h,600000.0,S,Maddison,4/03/2017,13.5,...,1,290.0,116.0,1980,Moonee Valley,-37.7273,144.8744,Western Metropolitan,3464,"-37.7273, 144.8744"
45,45,Airport West,54 Marshall Rd,3,h,720000.0,S,Barry,6/08/2016,13.5,...,1,620.0,126.0,1970,Moonee Valley,-37.7173,144.8872,Western Metropolitan,3464,"-37.7173, 144.8872"
46,46,Airport West,36 Roberts Rd,4,h,785000.0,S,Considine,6/08/2016,13.5,...,2,597.0,127.0,1970,Moonee Valley,-37.7259,144.8792,Western Metropolitan,3464,"-37.7259, 144.8792"

Средняя цена здания: 743093