In [8]:
import pandas as pd

teclo_data = pd.read_csv('data/Telco_Customer_Churn.csv')
teclo_df = teclo_data.copy()

#teclo_df.head()
#teclo_df.info()
teclo_df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

2. Чистка данных

- найти пропуски (isnull().sum())
- заменить пропуски:
 - числовые → медиана
 - категориальные → "Unknown"

цель: базовая подготовка

In [12]:
print(teclo_df.isnull().sum())

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

3. Фильтрация

найти клиентов:
- у которых MonthlyCharges > 70
- и Contract == "Month-to-month"

👉 цель: логические условия

In [15]:
teclo_df_fitred = teclo_df[teclo_df['MonthlyCharges'] > 70][teclo_df['Contract'] == 'Month-to-month']

display(teclo_df_fitred)

C:\Users\Nitro\AppData\Local\Temp\ipykernel_19664\3583751125.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  teclo_df_fitred = teclo_df[teclo_df['MonthlyCharges'] > 70][teclo_df['Contract'] == 'Month-to-month']

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
13,0280-XJGEX,Male,0,No,No,49,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0550-DCXLH,Male,0,No,No,13,Yes,No,DSL,No,...,No,Yes,Yes,Yes,Month-to-month,No,Mailed check,73.35,931.55,No
7032,6894-LFHLY,Male,1,No,No,1,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,75.75,75.75,Yes
7034,0639-TSIQW,Female,0,No,No,67,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),102.95,6886.25,Yes
7035,8456-QDAVC,Male,0,No,No,19,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Bank transfer (automatic),78.70,1495.1,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes

4. Feature Engineering

создай новые колонки:

- total_spent = tenure * MonthlyCharges
- is_senior = 1 если SeniorCitizen == 1 иначе 0

👉 цель: работа с колонками

In [ ]:
teclo_df['total_spent'] = teclo_df['tenure'] * teclo_df['MonthlyCharges']

for col in teclo_df['SeniorCitizen']:
   if col == 1:
      teclo_df['is_senior'] = 1
   else:
      teclo_df['is_senior'] = 0

teclo_df['is_senior']

TypeError: 'RangeIndex' object is not callable