In [36]:
melb_df

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Lattitude,Longtitude,Regionname,Propertycount,Coordinates,Year,Month,PricePerRoom,AgeAtSale,IsExpensive
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,2016-12-03,2.5,...,-37.79960,144.99840,Northern Metropolitan,4019,"-37.7996, 144.9984",2016,12,740000.000000,46,1
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,2016-02-04,2.5,...,-37.80790,144.99340,Northern Metropolitan,4019,"-37.8079, 144.9934",2016,2,517500.000000,116,1
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,2017-03-04,2.5,...,-37.80930,144.99440,Northern Metropolitan,4019,"-37.8093, 144.9944",2017,3,488333.333333,117,1
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,2017-03-04,2.5,...,-37.79690,144.99690,Northern Metropolitan,4019,"-37.7969, 144.9969",2017,3,283333.333333,47,0
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,2016-06-04,2.5,...,-37.80720,144.99410,Northern Metropolitan,4019,"-37.8072, 144.9941",2016,6,400000.000000,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,2017-08-26,16.7,...,-37.90562,145.16761,South-Eastern Metropolitan,7392,"-37.90562, 145.16761",2017,8,311250.000000,36,1
13576,13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,2017-08-26,6.8,...,-37.85927,144.87904,Western Metropolitan,6380,"-37.85927, 144.87904",2017,8,343666.666667,22,1
13577,13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,2017-08-26,6.8,...,-37.85274,144.88738,Western Metropolitan,6380,"-37.85274, 144.88738",2017,8,390000.000000,20,1
13578,13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,2017-08-26,6.8,...,-37.85908,144.89299,Western Metropolitan,6380,"-37.85908, 144.89299",2017,8,625000.000000,97,1
13579,13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,2017-08-26,6.3,...,-37.81188,144.88449,Western Metropolitan,6543,"-37.81188, 144.88449",2017,8,321250.000000,97,1

- Сколько строк и столбцов?
- Какие колонки имеют пропуски и сколько?
- Выведи статистику (mean/std/min/max) только для числовых колонок
- Какой процент пропусков в CouncilArea?

In [20]:
import pandas as pd

melb_data = pd.read_csv('data/melb_data.csv')
melb_df = melb_data.copy()
# melb_df.info()
#melb_df.describe()
# в каких колонках пропущены значения
col_miss = melb_df.columns[melb_df.isna().any()]
# строк пропущенных в CouncilArea
missing_count = melb_df['CouncilArea'].isna().sum()
# среднее минимальное и максимальное значения в числовых колонках
melb_df.select_dtypes(include='number').describe().loc[['mean','std','min','max']]
# процент пропусков в колонке CouncilArea

percent_missing = (missing_count / len(melb_df)) * 100
print(percent_missing)

10.08100147275405

- Найди все объекты с ценой выше 2 млн
- Найди дома (Type = 'h') с 4+ комнатами И расстоянием до центра < 10 км
- Выведи уникальные районы (Suburb), где продавалось более 100 объектов

In [2]:
# с ценой от 2 млн
two_m_price= melb_df[melb_df['Price'] > 2000000]
# display(two_m_price.head())
# дома типа h с 4 и более комнатами и растоянием до центра не более 10 
h_four_rooms = melb_df[(melb_df['Type'] == 'h') & (melb_df['Rooms'] >= 4) & (melb_df['Distance'] <= 10)]
#h_four_rooms.head()
# уникальные районы в которых продалось более 100 домов
districts_one_hundred = melb_df.groupby('Suburb').filter(lambda x: len(x) > 100).Suburb.unique()
display(districts_one_hundred)

<StringArray>
[    'Ascot Vale',         'Balwyn',   'Balwyn North',      'Bentleigh',
 'Bentleigh East',       'Brighton',  'Brighton East',      'Brunswick',
 'Brunswick West',     'Camberwell',       'Carnegie',         'Coburg',
      'Doncaster',         'Elwood',       'Essendon',      'Footscray',
      'Glen Iris',        'Glenroy',        'Hampton',       'Hawthorn',
    'Keilor East',     'Kensington',            'Kew',   'Malvern East',
   'Moonee Ponds',        'Newport',      'Northcote',    'Pascoe Vale',
 'Port Melbourne',        'Prahran',        'Preston',      'Reservoir',
       'Richmond',    'South Yarra',       'St Kilda',       'Sunshine',
   'Surrey Hills',      'Thornbury',   'Williamstown',     'Yarraville',
        'Fawkner',  'Hawthorn East', 'West Footscray']
Length: 43, dtype: str

- Средняя цена по типу недвижимости (Type)
- Медианная цена по региону (Regionname) — отсортируй по убыванию
- Сколько объектов продал каждый агент (SellerG)? Выведи топ-10

In [ ]:
# средняя цена в зависимости от типа дома
mask_dfprice_type = melb_df.groupby('Type')['Price'].mean()
mask_dfprice_type
# медианная цена в зависимости от района
mask_dfmedian_price_region = melb_df.groupby('Regionname')['Price'].median().sort_values(ascending=False)
mask_dfmedian_price_region
#
counted_sellers_objects = melb_df.groupby('SellerG')['Type'].count().sort_values(ascending=False) 
display(counted_sellers_objects.head(10))

SellerG
Nelson           1565
Jellis           1316
hockingstuart    1167
Barry            1011
Ray               701
Marshall          659
Buxton            632
Biggin            393
Brad              342
Fletchers         301
Name: Type, dtype: int64

- Создай таблицу: строки = Regionname, столбцы = Type (h/u/t),
  значения = средняя цена. Используй pivot_table()
- В каком регионе самая большая разница в цене между h и u?

In [17]:
sorted_df = melb_df.pivot_table(index='Regionname',columns='Type', aggfunc={'Price':'mean'})
sorted_df['diff_h_u'] = sorted_df['Price']['h'] - sorted_df['Price']['u']
sorted_df = sorted_df.sort_values(by='diff_h_u', ascending=False)
display(sorted_df.head(10))

                                   Price                               \
Type                                   h             t              u
Regionname
Southern Metropolitan       1.802241e+06  1.205404e+06  664860.005165
Eastern Metropolitan        1.197450e+06  8.696199e+05  649314.444444
Northern Metropolitan       1.021222e+06  7.496083e+05  544403.774427
Western Metropolitan        9.507663e+05  7.209510e+05  488414.424821
South-Eastern Metropolitan  9.559496e+05  9.132700e+05  583364.864865
Eastern Victoria            7.142996e+05           NaN  461333.333333
Northern Victoria           5.948293e+05           NaN            NaN
Western Victoria            3.975234e+05           NaN            NaN

                                diff_h_u
Type
Regionname
Southern Metropolitan       1.137381e+06
Eastern Metropolitan        5.481360e+05
Northern Metropolitan       4.768181e+05
Western Metropolitan        4.623518e+05
South-Eastern Metropolitan  3.725848e+05
Eastern Victoria            2.529663e+05
Northern Victoria                    NaN
Western Victoria                     NaN

- Заполни пропуски в CouncilArea значением 'Unknown'
- Заполни пропуски в Bedroom, Bathroom, Car медианой по каждому столбцу
- После заполнения проверь: df.isnull().sum() должен вернуть 0

In [30]:
# замена пропущенных значений в колонке CouncilArea на 'Unknown'
melb_df['CouncilArea'] = melb_df['CouncilArea'].fillna('Unknown')
# замена пропущенных значений в колонке Bedroom, Bathroom, Car на медианное значение
melb_df['Bedroom'] = melb_df['Bedroom'].fillna(melb_df['Bedroom'].median())
melb_df['Bathroom'] = melb_df['Bathroom'].fillna(melb_df['Bathroom'].median())
melb_df['Car'] = melb_df['Car'].fillna(melb_df['Car'].median())

melb_df.isnull().sum()

index            0
Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Distance         0
Postcode         0
Bedroom          0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
CouncilArea      0
Lattitude        0
Longtitude       0
Regionname       0
Propertycount    0
Coordinates      0
dtype: int64

- Переведи колонку Date в datetime
- Создай новые колонки: Year (год продажи), Month (месяц)
- Найди: в каком месяце продавалось больше всего объектов?

In [34]:
# преобразование колонки Date в формат datetime и создание новых колонок Year и Month
melb_df['Date'] = pd.to_datetime(melb_df['Date'], dayfirst=True)
melb_df['Year'] = melb_df['Date'].dt.year
melb_df['Month'] = melb_df['Date'].dt.month
# средняя цена в зависимости от месяца продажи
avg_price_month = melb_df.groupby('Month')['Price'].mean()
display(avg_price_month)

Month
1     1.009000e+06
2     1.104372e+06
3     1.141256e+06
4     1.018167e+06
5     1.095086e+06
6     1.076351e+06
7     8.995594e+05
8     1.140499e+06
9     1.133612e+06
10    1.065341e+06
11    1.117513e+06
12    1.170918e+06
Name: Price, dtype: float64

- Создай колонку PricePerRoom = Price / Rooms
- Создай колонку AgeAtSale = год продажи - YearBuilt
- Создай бинарный флаг IsExpensive: 1 если цена > медианной цены, иначе 0

In [35]:
# средняя цена за комнату
melb_df['PricePerRoom'] = melb_df['Price'] / melb_df['Rooms']
# возраст дома на момент продажи
melb_df['AgeAtSale'] = melb_df['Year'] - melb_df['YearBuilt']
# маркировка дорогих домов
melb_df['IsExpensive'] = melb_df.apply(lambda x: 1 if x['Price'] > melb_df['Price'].median() else 0, axis=1)